"""Capture one real replay run's emitted spans as data for the visuals (#60).

No new instrumentation: this runs the *same* `toyworld.replay` through the same
Gradebook library, swapping only the exporter - an in-memory one instead of
OTLP - exactly as the test suite does. Every span, attribute and span link here
is the one that would have gone to SigNoz.

    python docs/visuals/capture_run.py

Writes `run-data.js` beside this file, which the visuals load as a plain
`<script>` tag so they open from `file://` with no server.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import ReadableSpan, TracerProvider
from opentelemetry.sdk.trace.export import SimpleSpanProcessor
from opentelemetry.sdk.trace.export.in_memory_span_exporter import InMemorySpanExporter

from toyworld.replay import replay
from toyworld.__main__ import RECORDING

HERE = Path(__file__).resolve().parent


def _provider(service_name: str, exporter: InMemorySpanExporter) -> TracerProvider:
    provider = TracerProvider(resource=Resource.create({"service.name": service_name}))
    provider.add_span_processor(SimpleSpanProcessor(exporter))
    return provider


def _hex_span(span_id: int) -> str:
    return format(span_id, "016x")


def _hex_trace(trace_id: int) -> str:
    return format(trace_id, "032x")


def _serialize(span: ReadableSpan, service: str) -> dict:
    ctx = span.get_span_context()
    assert ctx is not None, f"finished span {span.name!r} has no span context"
    return {
        "service": service,
        "name": span.name,
        "traceId": _hex_trace(ctx.trace_id),
        "spanId": _hex_span(ctx.span_id),
        "parentSpanId": _hex_span(span.parent.span_id) if span.parent else None,
        "startUnixNano": span.start_time,
        "endUnixNano": span.end_time,
        "attributes": dict(span.attributes or {}),
        # Span-link Role 1: a late reality grade points back at the decision
        # span it judges. This is the edge span-link.html walks.
        "links": [
            {
                "traceId": _hex_trace(link.context.trace_id),
                "spanId": _hex_span(link.context.span_id),
            }
            for link in (span.links or ())
        ],
    }


def capture() -> dict:
    world_exporter = InMemorySpanExporter()
    outcomes_exporter = InMemorySpanExporter()
    world = _provider("toy-world", world_exporter)
    outcomes = _provider("toy-world-outcomes", outcomes_exporter)

    summary = replay(RECORDING, world_provider=world, outcomes_provider=outcomes)

    spans = [_serialize(s, "toy-world") for s in world_exporter.get_finished_spans()]
    spans += [
        _serialize(s, "toy-world-outcomes")
        for s in outcomes_exporter.get_finished_spans()
    ]
    spans.sort(key=lambda s: s["startUnixNano"])

    return {
        "recording": RECORDING.name,
        "capturedAt": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "summary": {
            "decisions": summary.decisions,
            "correct": summary.correct,
            "outcomes": summary.outcomes,
            "totalCostUsd": summary.total_cost_usd,
            "costPerCorrectUsd": summary.cost_per_correct_usd,
        },
        "spans": spans,
    }


def _check(run: dict) -> None:
    """The visuals are only honest if the link they walk is really in the data.

    Cheap self-check rather than a test file: docs/ is not a package, so a
    pytest here would never run in CI. If the recorder ever stops emitting the
    section-6 span link, this fails loudly instead of rendering an empty radius.
    """
    ids = {s["spanId"] for s in run["spans"]}
    reality = [
        s
        for s in run["spans"]
        if s["attributes"].get("augmentloop.grade.source") == "reality"
    ]
    assert reality, "no reality grades captured - nothing for the visuals to attribute"
    for s in reality:
        assert len(s["links"]) == 1, f"reality grade {s['spanId']} lost its span link"
        assert s["links"][0]["spanId"] in ids, "span link points outside the capture"
        assert s["links"][0]["traceId"] != s["traceId"], (
            "the link is supposed to cross a trace boundary - that is the point"
        )


def main() -> None:
    run = capture()
    _check(run)
    out = HERE / "run-data.js"
    out.write_text(
        "// Generated by capture_run.py from a real replay run - do not hand-edit.\n"
        "window.RUN = " + json.dumps(run, indent=2) + ";\n",
        encoding="utf-8",
    )
    linked = sum(1 for s in run["spans"] if s["links"])
    print(f"{len(run['spans'])} spans ({linked} carrying span links) -> {out}")


if __name__ == "__main__":
    main()
